# Generated by Django 3.1.6 on 2021-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookst', '0002_auto_20210211_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '기타'), (1, '소설'), (2, '시/에세이'), (3, '경제/경영'), (4, '자기계발')], default=0, verbose_name='종류'),
            preserve_default=False,
        ),
    ]
