# Generated by Django 3.1.6 on 2021-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookst', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='bookst/default/기본이미지.jpg', upload_to='bookst/image'),
        ),
    ]
